//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Personnel
{
	public virtual object numINSEE
	{
		get;
		set;
	}

	public virtual object nom
	{
		get;
		set;
	}

	public virtual object salaire
	{
		get;
		set;
	}

	public virtual Fonction Fonction
	{
		get;
		set;
	}

}

