//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Reservoir
{
	public virtual double Capacite
	{
		get;
		set;
	}

	public virtual double Contenu
	{
		get;
		set;
	}

	public Reservoir(int puissance)
	{
        if (puissance <= 6) Capacite = 40;
        else Capacite = 60;

        Contenu = Capacite;
	}

	public virtual void Diminuer(double conso, double nbKm)
	{
        Contenu = Contenu - nbKm * conso / 100;
	}

	public double DistanceMaxi(double conso)
	{
        return (Capacite / conso) * 100;
	}

	public virtual void Remplir()
	{
        if (Capacite == 40) Contenu = 40;
        else Capacite = 60;
    }
    
}

