//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Aliment
{
	public virtual object codebarres
	{
		get;
		set;
	}

	public virtual object nom
	{
		get;
		set;
	}

	public virtual object prix
	{
		get;
		set;
	}

	public virtual IEnumerable<Fournisseur> Fournisseur
	{
		get;
		set;
	}

}

