//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Animal
{
	public virtual int num
	{
		get;
		set;
	}

	public virtual string nom
	{
		get;
		set;
	}

	public virtual object see
	{
		get;
		set;
	}

	public virtual object poids
	{
		get;
		set;
	}

	public virtual Famille Famille
	{
		get;
		set;
	}

	public virtual IEnumerable<Quantité> Quantité
	{
		get;
		set;
	}

	public virtual Habitat unHabitat
	{
		get;
		set;
	}

	public virtual IEnumerable<Soin> Soin
	{
		get;
		set;
	}

	public virtual int M1(int Parameter1, double Parameter2)
	{
		throw new System.NotImplementedException();
	}

}

