//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Habitat
{
	public virtual object num
	{
		get;
		set;
	}

	public virtual object superficie
	{
		get;
		set;
	}

	public virtual object cloture
	{
		get;
		set;
	}

	public virtual TypeHabitat TypeHabitat
	{
		get;
		set;
	}

}

