//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Consommation
{
	public virtual int NbLitres
	{
		get;
		set;
	}

	public virtual double Prix
	{
		get;
		set;
	}

	public virtual int Panne
	{
		get;
		set;
	}

	public virtual Compteur Compteur
	{
		get;
		set;
	}

}

