//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Voyage
{
	public virtual double cout
	{
		get;
		set;
	}

	public virtual int longueur
	{
		get;
		set;
	}

	public virtual Voiture Voiture
	{
		get;
		set;
	}

}

